version: '3'

services:
  web:
    build:
      ./odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo:rw,Z
      - ./addons:/mnt/extra-addons:rw,Z
    environment:
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
      - ODOO_DB_NAME=odoodb
      - ODOO_DB_HOST=db
      - ODOO_ADMIN_PASSWORD=randompass
    tty:
      true
  db:
    image:
      postgres:9.6
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTRGES_DB=odoodb
    volumes:
      - odoo-db-data:/var/lib/postgresql/data:rw,Z
volumes:
  odoo-db-data:
  odoo-web-data:
